spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trust_trade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your-db-username
    password: your-db-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: your-redis-host
      port: 6379

nts:
  api:
    url: https://api.odcloud.kr/api/nts-businessman/v1/validate
    service-key: your-nts-service-key

kakao:
  api:
    service-key: your-kakao-service-key

payment:
  toss:
    test-client-api-key: your-toss-client-api-key
    test-secret-key: your-toss-secret-key

geocoding:
  kakao:
    base-url: https://dapi.kakao.com
    rest-api-key: your-kakao-rest-api-key